10 PRINT "PROGRAM FILE 162: ERROR - REFERENCE TO FUNCTION PRECEDES"
20 PRINT "        ITS DEFINITION."
30 PRINT "    ANSI STANDARD 16.4"
40 PRINT
50 PRINT "SECTION 163.1: ERROR - REFERENCE TO FUNCTION PRECEDES"
60 PRINT "        ITS DEFINITION."
70 PRINT
80 PRINT "THIS SECTION TESTS WHAT HAPPENS WHEN A USER FUNCTION IS"
90 PRINT "INVOKED IN A LOWER-NUMBERED LINE THAN THE DEF STATEMENT"
100 PRINT "FOR THAT FUNCTION."
110 PRINT
120 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
130 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
140 PRINT
150 PRINT "   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
160 PRINT "      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
170 PRINT "      BY THE PROCESSOR, OR"
180 PRINT
190 PRINT "   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
200 PRINT
210 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
220 PRINT "FOR DETAILED CRITERIA."
230 PRINT
240 PRINT "             BEGIN TEST."
250 PRINT
260 PRINT "(LATER) DEFINITION OF FND(R)=R+10"
270 PRINT
280 PRINT "ABOUT TO ATTEMPT INVOCATION OF FND(5)."
290 LET A=FND(5)
300 PRINT "PROCESSOR HAS EVALUATED FND(5) = ";A
310 PRINT
320 DEF FND(R)=R+10
330 PRINT "              END TEST"
340 PRINT
350 PRINT "END PROGRAM 162"
360 END
