0 PRINT "A STATEMENT WITH A LINE-NUMBER OF 0 HAS BEEN EXECUTED."
10 PRINT
20 PRINT "PROGRAM FILE 2000: ERROR - LINE-NUMBER ZERO."
30 PRINT "    ANSI STANDARD 4.4"
40 PRINT
50 PRINT "SECTION 200.1: ERROR - LINE-NUMBER ZERO."
60 PRINT
170 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
180 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
190 PRINT
200 PRINT "   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
210 PRINT "      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
220 PRINT "      BY THE PROCESSOR, OR"
230 PRINT
240 PRINT "   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
250 PRINT
260 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
270 PRINT "FOR DETAILED CRITERIA."
280 PRINT
1070 PRINT "                              BEGIN TEST."
1080 PRINT
1090 PRINT "THIS PROGRAM TESTS TO SEE IF THE PROCESSOR ACCEPTS PROGRAMS"
1100 PRINT "CONTAINING LINE-NUMBERS WITH THE VALUE OF 0. THE FIRST"
1110 PRINT "STATEMENT IN THIS PROGRAM HAS A LINE-NUMBER OF 0. IT IS A"
1120 PRINT "PRINT-STATEMENT WHICH PRINTS THE MESSAGE THAT A LINE-NUMBER"
1130 PRINT "OF 0 HAS BEEN EXECUTED. CHECK THE FIRST LINE OF OUTPUT."
1140 PRINT
1150 PRINT "                               END TEST."
1160 PRINT
1290 PRINT "END PROGRAM 200"
1300 END
