# ---------------------------------------------------------------------------
# Copyright (C) 2023 Jorge Giner Cordero
# This file is part of bas55 (ECMA-55 Minimal BASIC System).
# bas55 license: GNU GPL v3 or later.
# ---------------------------------------------------------------------------

newton:	newton.c
	cc -Wall -lm -o newton newton.c
