# ---------------------------------------------------------------------------
# Copyright (C) 2023 Jorge Giner Cordero
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
# ---------------------------------------------------------------------------

newton:	newton.c
	cc -Wall -lm -o newton newton.c
